name: Deploy Managed Identity
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  deploy-managed-identity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Managed Identity
      run: |
        az deployment group create --resource-group GCS_ManagedIdentitytest7rd --template-file resourceGroup.bicep --parameters resourceGroup.parameters.json
