name: Deploy Managed Identity and Restart Azure Web App

on: 
  push:
    branches:
      - main # Trigger the workflow on push to the main branch

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: SREtestS_group
  WEB_APP_NAME: SREtest

jobs:
  deploy-managed-identity:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SUB_PAYG }}

    - name: Restart Azure Web App
      run: |
        az webapp restart --name ${{ env.WEB_APP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}
